services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./z_mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpass
      - MYSQL_DATABASE=laravel

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1